"""changes

Revision ID: 25bad2569f8d
Revises: b7a133189d73
Create Date: 2025-05-12 14:42:17.651514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25bad2569f8d'
down_revision = 'b7a133189d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('attack', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('defense', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_column('defense')
        batch_op.drop_column('attack')
        batch_op.drop_column('hp')

    # ### end Alembic commands ###
